version: '3.9'

services:
  fuel-explorer:
    platform: linux/amd64
    container_name: fuel-explorer
    image: ${FUEL_EXPLORER_PREVIEW_IMAGE}
    env_file:
      - .env
    environment:
      FUEL_PROVIDER_URL: 'http://beta-4.fuel.network/graphql'
    ports:
      - '80:3000'
      - '4000:4444'
