import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StylesRegistry from '~/systems/Core/components/StylesRegistry';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <StylesRegistry>
        <body>{children}</body>
      </StylesRegistry>
    </html>
  );
}
