name: "CI setup"
description: "Setup NodeJS and PNPM"

inputs:
  node-version:
    description: "Node version"
    default: 18.14.1
  pnpm-version:
    description: "PNPM version"
    default: latest

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        DIR=$(pnpm store path --silent)
        echo "TURBO_CACHE_DIR=$DIR/.turbo" >> $GITHUB_ENV
        echo "STORE_PATH=$DIR" >> $GITHUB_ENV

    - name: Cache turbo build setup
      uses: actions/cache@v3
      with:
        path: ${{ env.TURBO_CACHE_DIR }}
        key: ${{ runner.os }}-turbo-${{ github.event.pull_request.number || github.ref }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ github.event.pull_request.number || github.ref }}
          ${{ runner.os }}-turbo-

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
      shell: bash
