apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fuel-explorer
  namespace: ${k8s_namespace}
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: fuel-explorer
  endpoints:
  - path: /api/metrics 
    port: http
