apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fuel-explorer.fullname" . }}
  labels:
    {{- include "fuel-explorer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fuel-explorer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fuel-explorer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fuel-explorer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "fuel-explorer.fullname" . }}
            - secretRef:
                name: {{ include "fuel-explorer.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /home/node/.cache
              name: node-cache
            - mountPath: /home/node/.pm2
              name: pm2
            - mountPath: /tmp
              name: tmp
            - mountPath: /app-explorer/dist
              name: dist
            - mountPath: /app-explorer/src/graphql
              name: graphql
            - mountPath: /app-explorer/node_modules
              name: node-modules
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: node-cache
          emptyDir: {}
        - name: pm2
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: dist
          emptyDir: {}
        - name: graphql
          emptyDir: {}
        - name: node-modules
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
