[package]
name = "predicate-app"
description = ""
version = "0.1.0"
edition = "2021"
authors = ["Fuel Labs"]
license = "Apache-2.0"

[dev-dependencies]
fuels = { version = "0.49", features = ["fuel-core-lib"] }
tokio = { version = "1.33", features = ["rt", "macros"] }
