/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';

import type { FuelMessagesEnabledUpgradeable } from '../FuelMessagesEnabledUpgradeable';

export class FuelMessagesEnabledUpgradeable__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FuelMessagesEnabledUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as FuelMessagesEnabledUpgradeable;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint8',
        name: 'version',
        type: 'uint8',
      },
    ],
    name: 'Initialized',
    type: 'event',
  },
  {
    inputs: [],
    name: 'fuelMessagePortal',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];
