/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';

import type { FuelMessagesEnabled } from '../FuelMessagesEnabled';

export class FuelMessagesEnabled__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FuelMessagesEnabled {
    return new Contract(address, _abi, signerOrProvider) as FuelMessagesEnabled;
  }
}

const _abi = [
  {
    inputs: [],
    name: 'fuelMessagePortal',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];
