# Run configurations see more https://github.com/FuelLabs/fuel-indexer/blob/master/config.yaml

run_migrations: true
graphql_api:
  host: '0.0.0.0'
  port: 29987
fuel_node:
  host: fuel-explorer-core
  port: 4000
database:
  postgres:
    user: postgres
    database: postgres
    password: postgres
    host: fuel-explorer-pgsql
    port: 5432
# Enable this once authentication is required
# authentication:
#   enabled: false
#   strategy: jwt
#   jwt_secret: abcdefghijklmnopqrstuvwxyz1234567890*
#   jwt_issuer: FuelLabs
#   jwt_expiry: 2592000
