name: Build and publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker-images:
    if: |
      (github.event_name == 'release' && github.event.action == 'published') ||
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository) ||
      github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        arch:
          - { platform: linux/amd64, runner: warp-ubuntu-latest-x64-4x }
          - { platform: linux/arm64, runner: warp-ubuntu-latest-arm64-4x }
    runs-on: ${{ matrix.arch.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/docker-publish
        with:
          phase: build-arch
          registry: ${{ env.REGISTRY }}
          image-repository: ${{ github.repository }}
          repository-owner: ${{ github.repository_owner }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: deployment/Dockerfile
          context: .
          platform: ${{ matrix.arch.platform }}

  publish-docker-images:
    needs: build-docker-images
    if: |
      (github.event_name == 'release' && github.event.action == 'published') ||
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/actions/docker-publish
        with:
          phase: publish-manifest
          registry: ${{ env.REGISTRY }}
          image-repository: ${{ github.repository }}
          repository-owner: ${{ github.repository_owner }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
