name: Build and publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker-images:
    if: |
      (github.event_name == 'release' && github.event.action == 'published') ||
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository) ||
      github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        arch:
          - { platform: linux/amd64, runner: warp-ubuntu-latest-x64-4x }
          - { platform: linux/arm64, runner: warp-ubuntu-latest-arm64-4x }
    runs-on: ${{ matrix.arch.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup environment
        run: |
          echo "REGISTRY_URL=${REGISTRY@L}/${IMAGE_NAME@L}" >> "${GITHUB_ENV}"
          platform=${{ matrix.arch.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> "${GITHUB_ENV}"

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_URL }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          file: deployment/Dockerfile
          platforms: ${{ matrix.arch.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=fuel-explorer-${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,scope=fuel-explorer-${{ env.PLATFORM_PAIR }},mode=max
          outputs: |
            type=image,name=${{ env.REGISTRY_URL }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  publish-docker-images:
    needs: build-docker-images
    if: |
      (github.event_name == 'release' && github.event.action == 'published') ||
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup environment
        run: |
          echo "REGISTRY_URL=${REGISTRY@L}/${IMAGE_NAME@L}" >> "${GITHUB_ENV}"

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_URL }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=
            type=semver,pattern={{raw}}

      - name: Create manifest list and push to ghcr.io
        working-directory: /tmp/digests
        env:
          DOCKER_METADATA_OUTPUT_JSON: ${{ steps.meta.outputs.json }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_URL }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_URL }}:${{ steps.meta.outputs.version }}
