name: Build and publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/fuel-explorer/Chart.yaml'

permissions:
  contents: read
  packages: write

jobs:
  helm-release:
    name: Build Helm Chart
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name:
