name: Build and Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/fuel-explorer/Chart.yaml'

permissions:
  contents: read
  packages: write  # `packages: write` burada belirtilmeli, çünkü paketlerin yazma izni gerekli.

jobs:
  helm-release:
    name: Build Helm Chart
    runs-on: ubuntu-22.04  # GitHub'un resmi bir runner'ını tercih ediyorum. Kendi runner'ınızı kullanıyorsanız bu kısmı değiştirebilirsiniz.
    if: |
      (github.event_name == 'release' && github.event.action == 'published') ||
      github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Package and Push Helm Chart
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url: oci://ghcr.io/fuellabs/helmcharts
          username: ${{ github.repository_owner }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: ./helm/fuel-explorer
