name: Deploy preview

on:
  pull_request:
    branches: [main]
    types: [labeled, unlabeled, synchronize, closed, reopened]

jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
      pull-requests: write
      statuses: write
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: pullpreview/action@v5.3.0
      with:
        app_path: .preview
        admins: luizstacio
        github_token: ${{ secrets.GITHUB_TOKEN }}
        always_on: main
      env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        AWS_REGION: "us-east-1"