name: "Release"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_VERSION: ""

jobs:
  release-changesets:
    name: Release master or rc
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: FuelLabs/github-actions/setups/node@v1  # master yerine sürüm sabitlendi
        with:
          node-version: 20.15.1
          pnpm-version: 9.5.0

      - uses: FuelLabs/github-actions/setups/npm@v1  # master yerine sürüm sabitlendi
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump and Collect Version
        run: |
          pnpm changeset version
          echo "BUILD_VERSION=$(pnpm -s packages:version)" >> $GITHUB_ENV
          git reset --hard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git user (for changelog step)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: FuelLabs/changesets-action@v1  # main yerine sürüm sabitlendi
        with:
          publish: pnpm changeset publish --tag next
          commit: "ci(changesets): versioning packages"
          title: "ci(changesets): versioning packages"
          createGithubReleases: aggregate
          githubReleaseName: v${{ env.BUILD_VERSION }}
          githubTagName: v${{ env.BUILD_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
